# Generated by Django 2.1.7 on 2019-07-31 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thisisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_user', models.TextField(max_length=200)),
                ('comment_text', models.TextField()),
                ('blog', models.ForeignKey(null=True, on_delete=True, to='thisisapp.Blog')),
            ],
        ),
    ]
