# Generated by Django 2.1.7 on 2019-08-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thisisapp', '0003_auto_20190802_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
