# Generated by Django 2.2.3 on 2019-08-09 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like1',
            field=models.ManyToManyField(blank=True, related_name='like1_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='like2',
            field=models.ManyToManyField(blank=True, related_name='like2_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
